language: node_js

node_js:
  - 10

os:
  - linux

#   sh -e /etc/init.d/xvfb start;
    # if [ $TRAVIS_OS_NAME == "linux" ]; then
    #   export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0
    #   /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    #   sleep 3
    # fi
before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

install:
  - npm install;


# before_script:
#   - npm run clean
script:
#  - echo 'skiiping test'
  - npm test

env:
  global:
    - TEMP=/home/travis/build/vincent-ledu/vscode-adr-tools-extension/testworkspace/
    - CODE_TESTS_WORKSPACE=/home/travis/build/vincent-ledu/vscode-adr-tools-extension/testworkspace/
    - secure: Vp/brluhqZVa+SM0E/aAOGbR+E1IgpQBfDgekRd5qftWVAb0jwoay7RLUeSqtaTvOmQrtD0csAGcOw8oVU08QFsoRljAykV3HBjHOMuvOGwqBGv8Vj0Cd8/CXsSPXro5OPq3IqiKNgChkEBAO0BssglFiZzQ+ycDLUI1EjGci67sZFQ9KfxxU+0w62qUJ8XQv9cu7l5cgZasYvhdbIjotBC1bNFQvMMID3s/ZAWcjrMooaV8yDgcH0sA8jfXupLDVgtpH/SdgIT6KAkXj6MS5/3E3L4FgSzVfEYNZmssyogKwx9meqoYGsDhRaHN6Vym32RmCh2VSmSBIIW2OArOuI+MNyxEL77DKzH0ox/ggJP01awcrkZl2Xdq/tmRntYfOJF7mPcl660oLMg1JmN2H8GbDKJoh0MvTQMSxzJ5D4+MhN5ViDTSihHzbsSbfkA/1LWTmWKD69zW7zKDksgl1nEv1KiUnT3s5bQl1s07s0LadeQVS9KJc5D8B6jXtHfSmQ0sH8OR3XSL1x0a2hhclorzcNwrmq5alOKLJ/+VSmrLb/z6kOAnjuZCWIpRxc7bjrdGqNc5RmhyRW4wM+AD24YKGZFMlSn6PH0biDvkGtFAfVjduUygrS/3zfLXiPmEd8vEyJnkG0dOtEvEKy3/ZaoqmEHRuWkKEHnuLbTucDA=

before_deploy:
  - npm install -g vsce;
  - vsce package;

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      repo: vincent-ledu/vscode-adr-tools-extension
      tags: true

  - provider: script
    script: vsce publish -p $VS_TOKEN
    skip_cleanup: true
    on:
      repo: vincent-ledu/vscode-adr-tools-extension
      tags: true
