language: node_js

node_js:
  - 10

os:
  - linux

#   sh -e /etc/init.d/xvfb start;
    # if [ $TRAVIS_OS_NAME == "linux" ]; then
    #   export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0
    #   /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    #   sleep 3
    # fi
before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

install:
  - npm install;


# before_script:
#   - npm run clean
script:
#  - echo 'skiiping test'
  - npm test

env:
  global:
    - TEMP=/home/travis/build/vincent-ledu/vscode-adr-tools-extension/testworkspace/
    - CODE_TESTS_WORKSPACE=/home/travis/build/vincent-ledu/vscode-adr-tools-extension/testworkspace/
    - secure: Nar/eohtQ1hW+/O9GpadGTAtAW6k3mwf5c22I0ysknTybUSeRL8MBrCCl8VyXB5JnzbhKZFGK1dcavet8d2CG3AxcsrEbiusCQitJ/P9XWCNobcioqlhglOmWI7d5E1eBRh4Vq0bNSgjuEiVjlm9j7kxxCyijLRY4JgcnxeotlD/ZgiIhKivMRTGPzrtnbK/4XY6u3Y115V3UiyGp1CoSxJpQ6A/K6cgxF9akaSjWO8BxUXZb7xJrLumVXIommNNovbQvZZwK+svp0IFUhifK2S3IsQf/2CUMaIbdVrMZT2loqe3G82tUuIwPw8pV9V8IUhghQBoc6OE3GqZpsLw7wNY33eRNPHysoH8vtESIpEKCawzDkxvRzYm3Kj410Gog4qIcjMgH60o7prstAQbsP+3SPwmEIoGAdCaoedbZEFCnOYkHpPasFEY9CB6GATFnjawSKsNMZMTqDNcYzXYQlM392chFqfjfIAmUGjF/I4v+H/r4usdk6VIbmctRE1BiSsS06wbbmIZuZMFNEsVyDGY4PMBurjtEsr2T0SVJN86CFDE0JUX+L3R+gndJeoyHXHPn1ssyrIgTC4k0/9lYVMOt2/ascI4Jr52waBv4P9ubhvaclyKWtZPE17LPa2aHPjox9T6pZLgdToPbMObUa+ol0AJ3AoI4UsW8JSo1gY=

before_deploy:
  - npm install -g vsce;
  - vsce package;

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      repo: vincent-ledu/vscode-adr-tools-extension
      tags: true

  - provider: script
    script: vsce publish -p $VS_TOKEN
    skip_cleanup: true
    on:
      repo: vincent-ledu/vscode-adr-tools-extension
      tags: true
